#!/bin/bash
# HTTP Endpoint Migration - Phase 1 Test Suite
# Tests all 7 new endpoints against running PPS server
#
# Usage: ./test_endpoints.sh [base_url]
# Default: http://localhost:8201

set -e

BASE_URL="${1:-http://localhost:8201}"
RESULTS_FILE="$(dirname "$0")/test_results.md"
PASSED=0
FAILED=0
TESTS=()

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=================================="
echo "PPS HTTP Endpoint Tests - Phase 1"
echo "=================================="
echo "Target: $BASE_URL"
echo "Started: $(date)"
echo ""

# Initialize results file
cat > "$RESULTS_FILE" << EOF
# HTTP Endpoint Test Results

**Date**: $(date "+%Y-%m-%d %H:%M:%S")
**Target**: $BASE_URL
**Tester**: test_endpoints.sh

## Summary

EOF

# Helper function to run a test
run_test() {
    local name="$1"
    local method="$2"
    local endpoint="$3"
    local data="$4"
    local expected_field="$5"

    echo -n "Testing: $name... "

    if [ "$method" = "GET" ]; then
        response=$(curl -s -w "\n%{http_code}" "$BASE_URL$endpoint")
    else
        response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            -d "$data" \
            "$BASE_URL$endpoint")
    fi

    http_code=$(echo "$response" | tail -n1)
    body=$(echo "$response" | sed '$d')

    # Check HTTP status and expected field
    if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
        if [ -n "$expected_field" ]; then
            if echo "$body" | grep -q "$expected_field"; then
                echo -e "${GREEN}PASS${NC} (HTTP $http_code)"
                TESTS+=("PASS: $name")
                ((PASSED++))
                echo "### $name" >> "$RESULTS_FILE"
                echo "" >> "$RESULTS_FILE"
                echo "- **Status**: PASS" >> "$RESULTS_FILE"
                echo "- **HTTP Code**: $http_code" >> "$RESULTS_FILE"
                echo "- **Endpoint**: \`$method $endpoint\`" >> "$RESULTS_FILE"
                echo "" >> "$RESULTS_FILE"
                echo "\`\`\`json" >> "$RESULTS_FILE"
                echo "$body" | head -c 1000 >> "$RESULTS_FILE"
                echo "" >> "$RESULTS_FILE"
                echo "\`\`\`" >> "$RESULTS_FILE"
                echo "" >> "$RESULTS_FILE"
                return 0
            else
                echo -e "${RED}FAIL${NC} (HTTP $http_code, missing '$expected_field')"
                TESTS+=("FAIL: $name - missing expected field")
                ((FAILED++))
            fi
        else
            echo -e "${GREEN}PASS${NC} (HTTP $http_code)"
            TESTS+=("PASS: $name")
            ((PASSED++))
            echo "### $name" >> "$RESULTS_FILE"
            echo "" >> "$RESULTS_FILE"
            echo "- **Status**: PASS" >> "$RESULTS_FILE"
            echo "- **HTTP Code**: $http_code" >> "$RESULTS_FILE"
            echo "- **Endpoint**: \`$method $endpoint\`" >> "$RESULTS_FILE"
            echo "" >> "$RESULTS_FILE"
            echo "\`\`\`json" >> "$RESULTS_FILE"
            echo "$body" | head -c 1000 >> "$RESULTS_FILE"
            echo "" >> "$RESULTS_FILE"
            echo "\`\`\`" >> "$RESULTS_FILE"
            echo "" >> "$RESULTS_FILE"
            return 0
        fi
    else
        echo -e "${RED}FAIL${NC} (HTTP $http_code)"
        TESTS+=("FAIL: $name - HTTP $http_code")
        ((FAILED++))
    fi

    # Log failure details
    echo "### $name" >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    echo "- **Status**: FAIL" >> "$RESULTS_FILE"
    echo "- **HTTP Code**: $http_code" >> "$RESULTS_FILE"
    echo "- **Endpoint**: \`$method $endpoint\`" >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    echo "**Response:**" >> "$RESULTS_FILE"
    echo "\`\`\`json" >> "$RESULTS_FILE"
    echo "$body" | head -c 2000 >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    echo "\`\`\`" >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    return 1
}

# Prereq: Health check
echo "--- Prerequisites ---"
run_test "Health Check" "GET" "/health" "" "healthy"
echo ""

# Phase 1 Endpoints
echo "--- Phase 1 Endpoints ---"

# 1. anchor_save - Save a word-photo
run_test "anchor_save" "POST" "/tools/anchor_save" \
    '{"content": "# Test Word-Photo\n\nA moment captured for testing HTTP endpoints.\n\n*Generated by test_endpoints.sh*", "title": "http-test-moment", "location": "test"}' \
    '"success":true'

# 2. crystallize - Create a crystal
run_test "crystallize" "POST" "/tools/crystallize" \
    '{"content": "# Test Crystal\n\nThis crystal verifies the HTTP endpoint works.\n\n## Key Points\n- HTTP endpoint functional\n- Created via curl\n- Should appear in crystal list"}' \
    '"success":true'

# 3. get_crystals - Retrieve recent crystals
run_test "get_crystals" "POST" "/tools/get_crystals" \
    '{"count": 2}' \
    '"crystals":'

# 4. texture_add - Add to knowledge graph
run_test "texture_add" "POST" "/tools/texture_add" \
    '{"content": "HTTP endpoint testing confirms the PPS system is working correctly. The test was run on a development machine.", "channel": "test"}' \
    '"success":true'

# 5. ingest_batch_to_graphiti - Batch ingest
run_test "ingest_batch_to_graphiti" "POST" "/tools/ingest_batch_to_graphiti" \
    '{"batch_size": 5}' \
    '"success":'

# 6. enter_space - Enter a space (may not find one)
run_test "enter_space" "POST" "/tools/enter_space" \
    '{"space_name": "main_room"}' \
    'success'

# 7. list_spaces - List all spaces
run_test "list_spaces" "GET" "/tools/list_spaces" "" \
    '"spaces":'

echo ""
echo "=================================="
echo "Test Results"
echo "=================================="
echo -e "Passed: ${GREEN}$PASSED${NC}"
echo -e "Failed: ${RED}$FAILED${NC}"
echo "Total:  $((PASSED + FAILED))"
echo ""

# Update summary in results file
sed -i "s/## Summary/## Summary\n\n- **Passed**: $PASSED\n- **Failed**: $FAILED\n- **Total**: $((PASSED + FAILED))\n/" "$RESULTS_FILE"

# Final verdict
if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}ALL TESTS PASSED${NC}"
    echo "" >> "$RESULTS_FILE"
    echo "---" >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    echo "**VERDICT: ALL TESTS PASSED**" >> "$RESULTS_FILE"
    exit 0
else
    echo -e "${RED}SOME TESTS FAILED${NC}"
    echo "" >> "$RESULTS_FILE"
    echo "---" >> "$RESULTS_FILE"
    echo "" >> "$RESULTS_FILE"
    echo "**VERDICT: $FAILED TEST(S) FAILED**" >> "$RESULTS_FILE"
    exit 1
fi
